server:
  port: 8082
  servlet:
    context-path: /myboot
debug: true
spring:
  datasource:
#    url: jdbc:sqlserver://192.168.1.100:1433;DatabaseName=MyTest
#    username: sa
#    password: AS441234873!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=MyTest
    username: sa
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
